### ISSUE TITLE
ModuleNotFoundError: No module named 'loopy.drivers.run_image'

### ISSUE THREAD

**Issue by sunjiahe-hub** [chaichontat/samui#89] opened 2023-05-04 03:19 UTC
Dear Support Team,

I am writing to inquire about an error that I encountered while attempting to load the GUI.  Specifically, I received the following error message: "ModuleNotFoundError: No module named 'loopy.drivers.run_image'".

I am unsure of the cause of this error or how to resolve it.  I have tried searching for a solution online, but have been unable to find one that addresses this specific issue.  As such, I am hoping that you can provide me with some guidance on how to proceed.

Sincerely，
Jia he

**Comment by chaichontat** [comment] 2023-05-07 23:50
Hi Jia he, thank you for your report. The issue is now fixed in a099b68.

**Closed by chaichontat** 2023-05-07 23:50 UTC
